spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BrysonBS/learning #远程仓库地址(即打开仓库后地址栏地址)
          search-paths: configuration #查询仓库内路径(文件夹)
          default-label: cloud # 仓库分支
          username: BrysonBS #用户名
          password: z147969  #密码
  application:
    name: config-server #定义应用名称
server:
  port: 8888 #服务启动端口