# spring:
#   datasource:
#     url: jdbc:sqlserver://10.0.0.25;DatabaseName=BPMDB
#     username: jtbys
#     password: nabel..bys

spring:
  #datasource:
  #  platform: h2
  #  url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
  #  schema:
  #    - classpath:data/schema.sql
  #  data:
  #    - classpath:data/data.sql
    # initialization-mode: always
  #jpa:
  #  show-sql: true
  #  hibernate:
  #    ddl-auto: update
  #main:
  #  allow-bean-definition-overriding: true

  profiles:
    active:
      - prod
  data:
    rest:
      base-path: /api
  jms:
    template:
      default-destination: cn.com.queue
  artemis:
    host: localhost
    port: 61616
    user: root
    password: root
    mode: embedded #使用内嵌服务器,需要额外引入artemis-jms-server
    embedded:
      persistent: true


server:
  port: 9090
  #port: 8443
  #ssl:
  #  key-store: classpath:mykeys.jks
  #  key-store-password: letmein
  #  key-password: letmein
stock:
  page-size: 15

---
spring:
  profiles: prod
  data:
    cassandra:
      keyspace-name: tacocloud
      #schema-action: recreate_drop_unused #启动时删除并重新创建表
      username: cassandra #默认用户名
      password: cassandra #默认密码
      contact-points:
        - localhost
        #- cassandra2.com.cn #其他服务器添加
      port: 9042 #默认端口
logging:
  level:
    root: WARN
    org.springframework.security: WARN

# git@github.com:BrysonBS/learning.git