# spring:
#   datasource:
#     url: jdbc:sqlserver://10.0.0.25;DatabaseName=BPMDB
#     username: jtbys
#     password: nabel..bys

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    schema:
      - classpath:data/schema.sql
    data:
      - classpath:data/data.sql
    # initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  profiles:
    active:
      - kafka
      #- prod
  data:
    rest:
      base-path: /api

server:
  port: 8443
  ssl:
    key-store: classpath:mykeys.jks
    key-store-password: letmein
    key-password: letmein
logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
  file:
    path: logs
stock:
  page-size: 15

---
spring:
  profiles: prod

logging:
  level:
    root: WARN
    org.springframework.security: WARN

---
spring:
  profiles: kafka
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: popInStock.topic
    consumer:
      group-id: test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "cn.tacos.tacocloud.domain.jpa"
        #spring.json.remove.type.headers: false
        #spring.json.use.type.headers: false
        spring.json.value.default.type: "cn.tacos.tacocloud.domain.jpa.PopInStock"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #properties:
        #spring.json.add.type.headers: false

# git@github.com:BrysonBS/learning.git