# spring:
#   datasource:
#     url: jdbc:sqlserver://10.0.0.25;DatabaseName=BPMDB
#     username: jtbys
#     password: nabel..bys

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    schema:
      - classpath:data/schema.sql
    data:
      - classpath:data/data.sql
    # initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  profiles:
    active:
      - prod
  data:
    rest:
      base-path: /api
  jms:
    template:
      default-destination: cn.com.queue
  artemis:
    host: localhost
    port: 61616
    user: root
    password: root
    mode: embedded #使用内嵌服务器,需要额外引入artemis-jms-server



server:
  port: 8443
  ssl:
    key-store: classpath:mykeys.jks
    key-store-password: letmein
    key-password: letmein
logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
  file:
    path: logs
stock:
  page-size: 15

---
spring:
  profiles: prod

logging:
  level:
    root: WARN
    org.springframework.security: WARN

# git@github.com:BrysonBS/learning.git