spring:
  cloud:
    config:
      uri:  http://localhost:8888 #定义从那个配置服务器(Config Server)获取配置属性
      # 默认值为http://localhost:8888
      profile: registry-RSA
      name: profiles
      #profile: eureka
      #label:
  #application:
  #  name: eureka-registry
  #profiles:
  #  active: registry