spring:
  profiles:
    active: eureka-registry
---
spring:
  profiles: eureka-registry
  application:
    name: eureka-registry
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka