spring:
  profiles: registry
  application:
    name: registry-profiles
server:
  port: '{cipher}0c4e97a951510731b47ab0bc81f62ceab517f28bec007e36c6a1654773c1d4a1' #8765使用123456密钥加密后
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
---
spring:
  profiles: registry-RSA
  application:
    name: registry-profiles-RSA
server:
  port: '{cipher}AQA2nYXUQe6c9TDSrAsJzFQKBEMykrp7w14KA5WZAKbFzaf+wHz3SKFwlyNHi2481bvscJ/ZOjR6IfWwOllDDeVf7WyzuvPEE+Mo4intWOqNkVXeGeB4qesgL+fJLO3VfU9mBV3pmn/yon0YfEd04NmjmgPUyFClxwIrCNeo/U41RvmPLXQ5mbZ8DYR2ao75zzlgOXCBgy0EYLBsqSb4M2/shcaCTe7rvvqq8sqEcefvQhBsgDrR3ujUyu4m+4LO1teFxZrsa0kTXrG2pl65FTN09EFtMOHJI0Ws3NN42l8Uv1Oa7r2OwqA0hOZKS6TJMObcFs8Rrpym9vuLuZpIab+kHbWrqcnsTQ2CRleu6OVMnUfXyhIbDAcEGMqaZ1wtrDs=' #8765使用RSA加密后
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
---
spring:
  profiles: registry-Vault
  application:
    name: registry-Vault
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
---
spring:
  profiles: consumer
  application:
    name: consumer
server:
  port: 8763
---
spring:
  profiles: taco
  application:
    name: taco
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    schema:
      - classpath:data/schema.sql
    data:
      - classpath:data/data.sql
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8767/eureka
greeting:
  message: Hello World!123